### ISSUE TITLE
General code review - March 2015

### ISSUE THREAD

**Issue by ethanwhite** [KristinaRiemer/MassResponseToTemp#1]
Overall this look really good. Nice use of functions, good docstrings, etc.

Here are a bunch of suggestions/requests for clarification. As you address them you should be able to simply check the boxes to indicate that you're done with that part.
- [x] Place all functions above executed code (and below imports)
- [x] Remove lines 12-13 when done with them
- [x] Remove #Functions comment on line 25 as function section will be clear
    based on standard position
- [x] Lines 58-61 can be replaced with `all_stackIDs = range(current_stackID, 0, -12)`
- [x] I would open the raster file outside of `get_temp_at_point` and then pass
    the opened file object to the function. Opening connections takes time,
    and you're doing this a lot here so it will make things more efficient.
    This is also a more standard approach because it makes code easier to
    test automatically (which we'll talk more at some point in the future)
- [x] Line 78: It is good to close files, though it would be a little strange
    that gdal doesn't given an explicit .Close() method. That said, as
    mentioned above, I'd recommend opening and closing this file once in the
    main body of the program. It's possible this will solve your problem.
- [x] In general, the style of commenting in `get_temp_at_point` would be
    considered too much documenting "mechanics" instead of "design &
    purpose". In some cases it's necessary to document mechanics, but in this
    case I think that most of the extra info in the comments could simply
    be integrated into the variable names. e.g., On line 81 the variable name
    could be changed to `temp_band` or `temp_band_array` and then remove the
    comment.
- [x] If you make the change recommended above then `get_temps_list` will also
    need to take the opened file object rather than the file name as input
- [ ] Since `get_temps_list` is fairly simple and is only called by
    `get_multiple_temps_lists` I would probably combine them.
- [ ] In general I find the temperature lookup code to be a bit confusing. I
    wonder if it can't be simplified. In addition to being difficult tor read
    I worry a bit about code that depends on unlabeled positions since it can
    be easy to make mistakes that way. Basically you're getting temperatures
    for different combinations of coordinates and bands. You could store
    these in a dictionary with the key being a tuple of the two coordinates
    and the band `(lat, long, band)` and the value being the temperature. This
    can be easily converted to a dataframe for merging with your existing
    dataframe using `pd.DataFrame.from_dict()`. `create_temp_dataset` should
    then just be a merge with `individual_data_subset()`.
- [ ] Line 120: Use `enumerate` instead of `range(len(all_stackIDs))`
- [ ] I applaud the attempt to make `plot_linreg` general, but as written it's
    a bit confusing to understand since `first_variable` and
    `second_vari_list` are hard to store logically. Since this function is
    only being used for one thing at the moment I might just go ahead and make
    the variable names more specific. Same general comment for
    `create_masstemp_plots` (espcially given that it's function name is very
    specific). e.g., `species_col` instead of `groupby_col_name`. Same for
    `get_multiple_state_lists`.
- [ ] The structure of `plot_linreg`, `get_r2_list`, and `get_slope_list` is
    confusing to me. Can you walk me through, in words, what you're doing.
    Then we might be able to find a more reable way to accomplish it.

**Comment by KristinaRiemer** [comment]
Code is much faster to run now from opening temperature raster file outside of the get_temp_at_point function, e.g., 6 minutes to 10 seconds. See 13cad21.

**Comment by KristinaRiemer** [comment]
See 895fb69 for some of these.

**Comment by KristinaRiemer** [comment]
This was likely all addressed with the analysis code rewrite early spring 2016 semester.
