### ISSUE TITLE
Expand specimen data

### ISSUE THREAD

**Issue by KristinaRiemer** [KristinaRiemer/MassResponseToTemp#15]
Need to find datasets of individual organisms that fulfill the current criteria for the project. 

Individual-level requirements: 
- Taxonomic ID to species
- Mass of individual
- Location of individual (either latitude or longitude or information that can be used to get latitude and longitude)
- Year (collection year for museum records)
- Adult

Species-level requirements:
- At least 30 individuals
- At least 5 degrees of latitude
- At least 20 years of data

Currently limited to years 1900 - 2010 because of temperature data, to United States because of easy latitude/longitude lookup using counties, and to mammals because of Smithsonian dataset. Could potentially expand any of these, and especially would like to expand to global extent.

**Comment by KristinaRiemer** [comment]
GBIF only has location information for individuals, but no mass data.

**Comment by KristinaRiemer** [comment]
Arctos (compilation of museum records from a bunch of museums including Berkeley) has specimens with species ID, location, and mass. The mass value is hidden within the "spec_locality" column though, as a number following the phrase WT. Makes it difficult to determine if there would be enough individuals with mass data to bother using the Arctos dataset. 

![arctos_mass_ex](https://cloud.githubusercontent.com/assets/6686508/10230457/1daeca60-684b-11e5-879b-3e18f0e6f41d.png)

**Comment by sdtaylor** [comment]
Is the requirement for 5 deg of latitude just to get a temperature gradient?

**Comment by KristinaRiemer** [comment]
Basically. This project started off being focused on Bergmann's rule, and studies on that pattern have oftentimes used latitude as a proxy for temperature. Now it's just to ensure there's enough of a range in temperatures.

**Comment by sdtaylor** [comment]
Would fish work? They would depend on water temp instead of air temp. But there is _loads_ of fish data from fish and game agencies in most states. Here is an example from Montana from streamnet.org. They sum up weights as averages, but you may be able to contact people to get raw data on individual weights. Stream water temperature is also studied a lot, and I'm pretty sure there are places to get it for most streams and rivers. 

![mt fish summary](https://cloud.githubusercontent.com/assets/12282062/10282934/54dab80c-6b4b-11e5-814b-fde7a7544a58.png)

**Comment by KristinaRiemer** [comment]
This is awesome! I'm currently using data on only terrestrial mammals, and therefore my temp dataset is also only terrestrial, so in the interest of ease I think I'm going to just stick to terrestrial animals for now. But later on if I decide to branch out and include aquatic animals (which I would like to do), I'll definitely check this stuff out.

**Comment by KristinaRiemer** [comment]
Vertnet seems to fulfill all of the criteria. Most (all?) of the specimens have species-level ID, latitude/longitude location, and year. A substantial portion of the specimens have weight (though it's again embedded in a column called "DynamicProperties"). There are also a lot of specimens. 

Created a new issue (#16) for the problems associated with getting this data.

**Comment by KristinaRiemer** [comment]
Vertnet fulfills all requirements and is global.
