### ISSUE TITLE
Clean Vertnet mammal data

### ISSUE THREAD

**Issue by KristinaRiemer** [KristinaRiemer/MassResponseToTemp#17]
Should be able to use code similar to that for cleaning the Smithsonian data (DatasetCleaningUS.R) to extract mass values from dynamicproperties column and subset dataset to only individuals that fulfill all of the requirements in issue #15.

**Comment by KristinaRiemer** [comment]
Cleaning tasks (from DatasetCleaningUS.R): 
- [x] Extract mass values from "dynamicproperties" column
- [x] Extract genus and species (if necessary)
- [x] Check genus and species using Taxize package
- [x] Use coordinates, if enough individuals have them, or do lat/lon lookup
- [x] Extract collection year (if necessary)
- [x] Subset dataset to contain only individuals with mass, species, coordinates, collection year 1900-2010, and adults
- [x] Create species list from subsetted dataset
- [x] Subset dataset again to contain only species with 30+ individuals, 20+ years, and 5+ latitudinal degrees
- [x] Check final dataset for outliers

**Comment by KristinaRiemer** [comment]
Received Vertnet trait extraction dump from Rob Guralnick on 12/11/15.

**Comment by KristinaRiemer** [comment]
Expect to have ~117,000 individuals of ~6,700 species from trait extraction after including only individuals with mass, taxonomic identification to species, coordinates, collection year, and life stage information. Don't have to geographically restrict analysis to United States.

**Comment by KristinaRiemer** [comment]
Based on current code, it would take ~185 hours to check taxonomy of entire Vertnet trait extraction (>950,000 rows). Clean rest of columns and subset dataset first to reduce number of rows.

**Comment by ethanwhite** [comment]
You should only need to check the taxonomy once for each unique species that shows up, so ~7000 checks not ~950K checks. You can do this either by getting the unique species names, checking their taxonomy, and then merging the corrected species names back into the main table, or by caching the correct species name once you'd looked it up and only hitting a name resolution service for raw species names that you haven't already checked.

**Comment by KristinaRiemer** [comment]
Done. See afc252d2.

**Comment by ethanwhite** [comment]
:+1:

**Comment by KristinaRiemer** [comment]
In final dataset, specimens where genus name = species name are real species. Don't need to subset based on individualcount because mostly = 1, where = 0 or 2 all seem to be typos because the dynamic properties are clearly taken for a single individual.
