### ISSUE TITLE
vertnet--only get necessary files?

### ISSUE THREAD

**Issue by davharris** [KristinaRiemer/MassResponseToTemp#25]
My spare computer has spent most of the day downloading/processing birds & mammals, which aren't used for this study if I understand correctly.  

Maybe the script should just grab the `vertnet-amphibians`, `vertnet-fishes` and `vertnet-reptiles` data sets and skip birds/mammals?

**Comment by davharris** [comment]
Also, I just got a warning about running out of disk space. Birds+mammals is about 20 gigabytes as a csv

**Comment by davharris** [comment]
Oh, never mind.  This is a different project than the one I was reading your manuscript for.  Carry on....

**Comment by KristinaRiemer** [comment]
I actually put in an issue on the Retriever about being able to download the 5 files separately ([here](https://github.com/weecology/retriever/issues/819)). I do end up using all but the fishes for this project though.

**Comment by KristinaRiemer** [comment]
Looks like they have incorporated this functionality, so I think I'm going to change the cleaning script to only download the bird, mammal, reptile, and amphibian datasets.
