### ISSUE TITLE
Remove rows with NAs while reading in raw data

### ISSUE THREAD

**Issue by KristinaRiemer** [KristinaRiemer/MassResponseToTemp#28]
Reading in the four full Vertnet csvs with read_csv takes too much memory (I let it run for three days and it didn't finish). I would like to read these csvs in using an R SQL interface and only selecting the rows that have a value in the mass column, which cuts down on the size of the files drastically. I've tried to use both sqldf and RSQLite R packages to do so, but they have difficulty dealing with commas within a cell (see [this](http://stackoverflow.com/questions/17057257/how-to-import-csv-into-sqlite-in-r-where-one-of-the-variables-has-a-comma-wi) for an example). I did this previously manually using DB Browser for SQLite as described in #23.

**Comment by ethanwhite** [comment]
I did a quick experiment with an SQLite database that contained:

```
a,b,c
1,2,"stuff,things"
3,4,"bill, jane"
```

using `dplyr` this seems to work fine:

```
> library(dplyr)
> db = src_sqlite("testme.sqlite")
> data = tbl(db, "testdata")
> data
Source:   query [?? x 3]
Database: sqlite 3.8.6 [testme.sqlite]

       a     b            c
   <chr> <chr>        <chr>
1      1     2 stuff,things
2      3     4   bill, jane
..   ...   ...          ...
```

You can either filter this with `dplyr` (which won't load all of the data it will do it all in the database) or you can use SQL with something like:

```
query = "SELECT * FROM testdata WHERE b=2"
data = tbl(db, sql(query))
```

If I'm missing something let me know and I'm happy to experiment some more.

**Comment by KristinaRiemer** [comment]
Sorry, I wasn't very clear in my initial comment, I kind of forgot you could see it. The problem I'm having is with turning csvs into SQLite tables. I run something like this:
`dbWriteTable(con, name = "sample_table", value = "data/temporary_sub.csv", row.names = FALSE, header = TRUE, sep = ",", eol = "\n")`

When `temporary_sub.csv` has commas in some rows like your example SQLite database, it throws this error: 
<img width="537" alt="screen shot 2017-04-18 at 2 04 37 pm" src="https://cloud.githubusercontent.com/assets/6686508/25145816/03f94e30-2440-11e7-9e0e-3215d559a017.png">

When I manually remove all the commas, it works just fine. This is the case both for dbWriteTable and sqldf's read.csv.sql. I haven't found anything helpful from Googling except that this has been a problem for other people. 

I could probably do this with sqlite3 in the command line? But not being able to do all of this within the R script would make everything more complicated. 

I didn't know dplyr has functionality to do SQL-type queries, that's cool.

**Comment by ethanwhite** [comment]
Why not just have the retriever install into SQLite in the first place?

**Comment by KristinaRiemer** [comment]
![facepalm](https://cloud.githubusercontent.com/assets/6686508/25151670/6ae94e6a-2454-11e7-8c35-56d98af3ecd8.jpeg)
Well that's embarassing, thanks for the help!

**Comment by ethanwhite** [comment]
😀👍

**Comment by KristinaRiemer** [comment]
See fcb711f
