### ISSUE TITLE
Ensure lin reg stats are accurate

### ISSUE THREAD

**Issue by KristinaRiemer** [KristinaRiemer/MassResponseToTemp#9]
Values from slope and r2 lists should correspond to stats figures.

**Comment by KristinaRiemer** [comment]
The problem with the statistics values is that the species with only 2 individuals currently are returning unexpected slopes (they're all different values but should be the same) and r2 (they're should all be zero but they're all the same non-zero value instead). The species with >2 individuals have sensible values though, so this might not be a problem when the whole dataset is run.

**Comment by ethanwhite** [comment]
You probably don't want to be fitting regressions to 2 data points anyway.

**Comment by KristinaRiemer** [comment]
True, but it's really weird. I don't think the statsmodels OLS function should be returning believable slopes and r2 of 0.9 for points that all have the same x values but different y values.

**Comment by KristinaRiemer** [comment]
Stats look fine for datasets with >2 individuals though.
